# Practice on Numpy and Pandas

Here are some task for you to refresh what you saw in the notebooks before.

It will help you strengthen the knowledge on Pandas and Numpy and will help you to understand how to:

- create NumPy arrays
- manipulate them with basic mathematics operators
- extract rows, columns and items by indexing
- use aggregation methods (like sum, min, max, std) on NumPy arrays

### Creating Numpy arrays

1. Please create a NumPy array from the list:

In [60]:
import numpy as np
my_list = [1,3,5,7,9]
numpy_array = np.array(my_list)
print(numpy_array)

[1 3 5 7 9]


```my_list = [1, 3, 5, 7, 9]```

2. Please create a NumPy array containing the values from 1 to 15.

In [4]:
numpy_array = np.arange(1, 16)
print(numpy_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


3. Please create a NumPy array from 0 to 8 with a step size of 0.3

In [61]:
numpy_array = np.arange(0, 8,0.3)
print(numpy_array)

[0.  0.3 0.6 0.9 1.2 1.5 1.8 2.1 2.4 2.7 3.  3.3 3.6 3.9 4.2 4.5 4.8 5.1
 5.4 5.7 6.  6.3 6.6 6.9 7.2 7.5 7.8]


4. Create a NumPy array with the shape 3,4 with random values

In [6]:
numpy_array = np.random.rand(3, 4)
print(numpy_array)

[[0.47637826 0.10570045 0.07570429 0.90000531]
 [0.54340731 0.9000311  0.96202513 0.01556572]
 [0.01990071 0.9154674  0.94246333 0.83055388]]


### Manipulate Numpy arrays

1. Please create a NumPy array with ```(1, 3, '5', 7, 9, '10')```. Define the content as integer.

In [86]:

numpy_array = np.array((1, 3, '5', 7, 9, '10'), np.int32) 
print(numpy_array)
type(numpy_array[2])

[ 1  3  5  7  9 10]


numpy.int32

2. Check the data type of the objects and the shape of the array

In [87]:
print(numpy_array.dtype)  #The data type of the elements in the array is int32, which means each element is a 32-bit integer.
print(numpy_array.shape)  #The shape is (6,), indicating it's a 1-dimensional array with 6 elements.

int32
(6,)


3. Update the 4th value to 8.

In [88]:
numpy_array[3] = 8
print(numpy_array)

[ 1  3  5  8  9 10]


4. Reshape the array to a (2x3) matrix.

In [89]:
reshape_array = numpy_array.reshape((2, 3))
print(reshape_array)

[[ 1  3  5]
 [ 8  9 10]]


5. Please add 8 to each value in the first row and 9 to each in the second row.

In [90]:
reshape_array = reshape_array + [[8],[9]]
print(reshape_array)

[[ 9 11 13]
 [17 18 19]]


6. Multiply the first column with 3, the second with 4 and the third with 5.

In [91]:

reshape_array = reshape_array * [3,4,5]
print(reshape_array)

[[27 44 65]
 [51 72 95]]


7. Please sum up all numbers in the first row, and all numbers in the second row.

In [92]:
reshape_array.sum(axis=1)

array([136, 218])

8. Similarly, search for the smallest number for each column.

In [93]:
reshape_array.min(axis=0)

array([27, 44, 65])

9. Extract the number in the second column and the first row.

In [94]:
print(reshape_array[0,1])

44


10. Check at which index the value is exactly 72.

In [ ]:
print(np.where(reshape_array == 72)) 

(array([1]), array([1]))


### More challenges!

1. Write a NumPy program to test element-wise for NaN of a given array.

In [35]:
import numpy as np

# Create an array with NaN values
arr = np.array([1, np.nan, 3, np.nan, 5])

# Test for NaN
nan_mask = np.isnan(arr)

print(nan_mask)

[False  True False  True False]


2. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [39]:


zeros = np.zeros(10, dtype=int)
ones = np.ones(10, dtype=int)
fives = np.full(10, 5)          #np.full(shape, fill_value, dtype=None)

# result = np.concatenate([zeros, ones, fives])
print(zeros)
print(ones)
print(fives)

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]


3. Write a NumPy program to create a 3X4 array and iterate over it.

In [96]:


# Create a 3x4 array
arr = np.arange(10,22).reshape((3, 4))

print("Array:")
print(arr)

print("\nIterate over each element:")
for x in np.nditer(arr):
  print(x,end=" ")


# for row in arr:
#     for elem in row:
#         print(elem, end=' ')
#     print()

Array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

Iterate over each element:
10 11 12 13 14 15 16 17 18 19 20 21 

4. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.

In [ ]:
#"Arbitrary values" just means any values you want — random or otherwise — that don’t follow a strict pattern or rule.

# np.random.rand() for random floats between 0 and 1,

# np.random.randint() for random integers,

# or simply np.arange() reshaped to (3,3,3).


arr = np.random.rand(3, 3, 3)
print(arr)

arr = np.random.randint(0, 10, size=(3, 3, 3))
print(arr)

arr = np.arange(27).reshape(3, 3, 3)
print(arr)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


5. Write a NumPy program to add a vector to each row of a given matrix

In [ ]:

# Create a 3x4 array
arr = np.arange(3,15).reshape((3, 4))
print(arr)
vector = np.array([10, 20, 30, 40])   #axis =1
result = arr + vector
print(result)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[13 24 35 46]
 [17 28 39 50]
 [21 32 43 54]]


In [97]:

m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]
